Automatically remove stale build label after the PR has been updated
oppia/oppiabot pull request #173
Opened 2020-12-17 11:51 UTC by jameesjohn

## Explanation

Remove the stale build label after the PR has been updated.

This feature has been tested at https://github.com/jameesjohn/oppia/pull/39.
## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2020-12-17 11:52 UTC, jameesjohn commented
This PR fails test for the same reason as #167.
I'm looking into it.

2020-12-17 13:45 UTC, vojtechjelinek requested changes
Thanks! A few comment.

2020-12-17 13:45 UTC, vojtechjelinek commented on lib/staleBuildChecks.js
> + * This function removes the old build label when a PR has a new push.
```suggestion
 * This function removes the old build label when a PR has a new commit.
```

2020-12-17 13:45 UTC, vojtechjelinek commented on spec/staleBuildChecksSpec.js
> +
Unneeded line

2020-12-17 22:11 UTC, jameesjohn commented on constants.js
>        mergeConflictCheck,
The `synchronize` event is also fired when there is a push to the main branch (develop)

2020-12-17 22:11 UTC, jameesjohn commented on lib/periodicChecks.js
> +  OLD_BUILD_LABEL
Nope. Removed.

2020-12-17 22:11 UTC, jameesjohn commented on lib/staleBuildChecks.js
> + * This function removes the old build label when a PR has a new push.
Done.

2020-12-17 22:11 UTC, jameesjohn commented on spec/staleBuildChecksSpec.js
> +
Removed.

2020-12-17 22:13 UTC, vojtechjelinek commented on constants.js
>        mergeConflictCheck,
But in that case, we don't want to remove the label since the tests are not restarted in that case, right?

2020-12-17 22:18 UTC, jameesjohn commented on constants.js
>        mergeConflictCheck,
Hmmm...
Yeah.
I'll update it to happen on push and not on synchronize.

2020-12-19 22:09 UTC, jameesjohn commented on constants.js
>        mergeConflictCheck,
Done.

2020-12-20 00:21 UTC, vojtechjelinek approved these changes
LGTM!

2020-12-20 00:22 UTC, merged

2020-12-20 00:22 UTC, vojtechjelinek commented
@jameesjohn could you please release this ASAP?

2020-12-20 08:02 UTC, jameesjohn commented
Done.