Fix #195 :Expose simple way to generate sheets token
oppia/oppiabot pull request #221
Opened 2021-03-23 16:15 UTC by jameesjohn

Fixes #195, exposes a simple way to generate google sheets API token for working with the CLA.
Tokens can be generated by running: `npm run sheets-setup`.
## Explanation

This PR has been tested at https://github.com/jameesjohn/comment-on-pr/pull/52
## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2021-03-23 20:09 UTC, vojtechjelinek requested changes
Thanks! Looks good to me, could you please ask one of our contributors to test this locally?

2021-03-27 07:40 UTC, gp201 commented
@jameesjohn @vojtechjelinek 
This is working locally. It has generated the access and refresh token and printed it in the console. 
However, can the variables in the `.env` file be made a bit more clear. Currently, I'm not sure where to place the Access token?

2021-03-27 23:25 UTC, jameesjohn commented
@gp201, the access token should be placed in the `CREDENTIALS` environment variable. 
 

> Also are we using the `SHEETS_API_CREDENTIALS` env variable for Oppiabot?

No, the `SHEETS_API_CREDENTIALS` env variable is not needed for Oppiabot. It can be deleted.

2021-03-28 00:19 UTC, vojtechjelinek commented
> @gp201, the access token should be placed in the `CREDENTIALS` environment variable.
> 
> > Also are we using the `SHEETS_API_CREDENTIALS` env variable for Oppiabot?
> 
> No, the `SHEETS_API_CREDENTIALS` env variable is not needed for Oppiabot. It can be deleted.

Can you add the info to the output of your script?

2021-04-06 13:36 UTC, jameesjohn commented
> Can you add the info about where to put the token to the output of your script

Done.

> And maybe to some wiki too?

I'm not sure where to add this.

2021-04-06 14:01 UTC, vojtechjelinek commented
> > Can you add the info about where to put the token to the output of your script
> 
> Done.
> 
> > And maybe to some wiki too?
> 
> I'm not sure where to add this.

Can you create a new page on this repo wiki?

2021-04-06 14:04 UTC, vojtechjelinek requested changes
Thanks, one comment.

2021-04-06 14:04 UTC, vojtechjelinek commented on .nycrc
> +  "exclude": ["./sheetsSetup.js"]
Why is this added?

2021-04-06 14:56 UTC, jameesjohn commented on .nycrc
> +  "exclude": ["./sheetsSetup.js"]
Removed.

2021-04-06 14:56 UTC, jameesjohn commented on .nycrc
> +  "exclude": ["./sheetsSetup.js"]
Removed.

2021-04-09 19:29 UTC, vojtechjelinek reviewed
LGTM!

2021-04-09 19:30 UTC, vojtechjelinek approved these changes
LGTM!

2021-04-11 06:22 UTC, jameesjohn commented
A new wiki page has been created: https://github.com/oppia/oppiabot/wiki/Setting-up-Google-Sheets

2021-04-11 06:22 UTC, merged