Added Steps for checking if node and npm is installed.
oppia/oppiabot pull request #246
Opened 2021-04-03 13:20 UTC by Naman-1234

## Explanation

Fixes #245 
## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2021-04-03 13:23 UTC, Naman-1234 commented
@vojtechjelinek  and @jameesjohn  Sir I think work in this PR is done. Please review this. Thanks.

2021-04-03 13:26 UTC, vojtechjelinek requested changes
Thanks, one comment.

2021-04-03 13:26 UTC, vojtechjelinek commented on README.md
> +    If these commands show some versions, then you can jump to Point No. 3, else proceed in this point:
```suggestion
    If these commands show some versions, then you can jump to Point No. 3, else proceed with these commands:
```

2021-04-03 13:36 UTC, Naman-1234 commented on README.md
> +    If these commands show some versions, then you can jump to Point No. 3, else proceed in this point:
Sure sir, Changing them right away.

2021-04-04 11:18 UTC, jameesjohn approved these changes
LGTM!

2021-04-04 20:11 UTC, merged