Removed line
oppia/oppiabot pull request #270
Opened 2021-05-25 16:24 UTC by Naman-1234

## Explanation

As suggested in the meeting, Line  is being disabled for now.  
## Checklist
- [x] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2021-05-26 23:42 UTC, vojtechjelinek commented
@Naman-1234 Frontend tests are failing

2021-05-27 10:52 UTC, Naman-1234 commented
@vojtechjelinek Yes Sir, They are failing as now the function call is commented, Should I just comment them as well or do anything else. Looking forward for a reply. Thanks.

2021-05-27 15:31 UTC, vojtechjelinek commented
@Naman-1234 Yeah, fix all the failures.

2021-05-27 16:48 UTC, Naman-1234 commented
@vojtechjelinek Oppiabot tests are passing now sir. Please take a review. Thanks.

2021-06-01 15:34 UTC, jameesjohn requested changes

2021-06-01 15:34 UTC, jameesjohn commented on index.js
>            case constants.periodicCheck:
Add `/* istanbul ignore next */` just before https://github.com/oppia/oppiabot/blob/65f1717d62f4f3358db40909e3c4228398ee14c1/lib/periodicChecks.js#L151
so it doesn't get counted for code  coverage

2021-06-01 15:34 UTC, jameesjohn commented on spec/periodicChecksSpec.js
> -    describe('When all issues have been added to a project', () => {
Instead of this, add `/* istanbul ignore next */` just before line 619. And change the `describe` there to `xdescribe`

2021-06-01 15:34 UTC, jameesjohn commented on index.js
>            case constants.periodicCheck:
Also add `/* istanbul ignore next */` to
https://github.com/oppia/oppiabot/blob/65f1717d62f4f3358db40909e3c4228398ee14c1/lib/utils.js#L364

and 

https://github.com/oppia/oppiabot/blob/65f1717d62f4f3358db40909e3c4228398ee14c1/lib/utils.js#L406

2021-06-10 12:12 UTC, jameesjohn commented
Hi @Naman-1234, any updates here?

2021-06-10 14:02 UTC, Naman-1234 commented
Sir, I added the changes requested earlier. Reason is the coverage area as discussed in the meeting. I tried to find in the codebase to remove spec from coverage portion(Which is the reason seems to be right now for failing tests). But I wasn't able to find it.

2021-06-10 16:27 UTC, Naman-1234 commented
@jameesjohn  Checks are passing now. Thanks.

2021-06-10 18:31 UTC, jameesjohn approved these changes
LGTM

2021-06-10 18:31 UTC, merged