Fix #304: Add check for hotfix label
oppia/oppiabot pull request #305
Opened 2022-03-31 14:38 UTC by ankita240796

## Explanation
Fixes #304: Adds a check for when hotfix label is added so that release team is ping and the PR is brought to their attention.

## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [x] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2022-04-04 14:03 UTC, vojtechjelinek requested changes
Thanks! One nit and on big picture comment.

2022-04-04 14:03 UTC, vojtechjelinek commented on lib/checkPullRequestLabels.js
> +    var CommentParams = context.issue({
```suggestion
    var commentParams = context.issue({
```

?

2022-04-12 15:04 UTC, ankita240796 commented on lib/utils.js
> +const HOTFIX_LABEL = 'PR: Needs to be hotfixed';
Sorry, I did not get this. Do you mean automatically add `PR: for current release` when the hotfix label is added?

2022-04-12 17:14 UTC, ankita240796 commented on lib/utils.js
> +const HOTFIX_LABEL = 'PR: Needs to be hotfixed';
Updated this as per our discussion.

2022-04-13 09:41 UTC, vojtechjelinek approved these changes
LGTM!

2022-04-13 11:03 UTC, ankita240796 commented
Hi @seanlip @vojtechjelinek can we please merge this one? Thanks!

2022-04-13 12:17 UTC, merged