Fix #320 Auto-assign reviewers for a PR when created
oppia/oppiabot pull request #330
Opened 2023-07-16 03:49 UTC by 462702985

## Explanation

wait 30s before oppiabot assign reviewers. github will have time to collect reviewers first.
## Checklist
- [ ] I have successfully deployed my own instance of Oppiabot.
  - You can find instructions for doing this [here](https://github.com/oppia/oppiabot/wiki/Deploying-your-own-instance-of-the-oppiabot).
- [ ] I have manually tested all the changes made in this PR following the [manual tests matrix](https://github.com/oppia/oppiabot/wiki/Manual-Tests-Matrix).

2023-07-16 18:44 UTC, U8NWXD commented
@seanlip who should review this PR? We need one approving review from someone with write access, but I don't know who those people are

2023-07-20 23:45 UTC, gp201 approved these changes
LGTM

2023-07-20 23:45 UTC, gp201 commented
@vojtechjelinek PTAL

2023-07-26 18:47 UTC, vojtechjelinek requested changes
Thanks! Just one comment.

2023-07-26 18:47 UTC, vojtechjelinek commented on lib/checkPullRequestLabels.js
> +  await utilityModule.sleep(30000);
Hmm, lets put a bit less, I think 10 seconds should be enough, 30 seconds wait can make the oppiabot timeout and not finish.

2023-08-02 07:28 UTC, vojtechjelinek commented
@462702985 When you fix something please reply to all the review comments and ping the reviewer again so that they know to do a review again.

2023-08-02 07:28 UTC, vojtechjelinek approved these changes
LGTM!

2023-08-02 07:28 UTC, merged